use vmax;
SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS `users` (
  `id` VARCHAR(191) NOT NULL,
  `team` VARCHAR(191) NULL,
  `role` VARCHAR(191) NULL,
  `password` TEXT NULL,
  `phone` TEXT NULL,
  `created_by` VARCHAR(191) NULL,
  `username` VARCHAR(191) NULL,
  `email` VARCHAR(191) NULL,
  `name` VARCHAR(191) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `managedTeam` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `targets` (
  `id` VARCHAR(191) NOT NULL,
  `monthlyTarget` BIGINT NULL,
  `agentName` VARCHAR(191) NULL,
  `agentId` VARCHAR(191) NULL,
  `dealsTarget` BIGINT NULL,
  `managerId` VARCHAR(191) NULL,
  `period` VARCHAR(191) NULL,
  `description` TEXT NULL,
  `updated_at` DATETIME NULL,
  `managerName` VARCHAR(191) NULL,
  `type` TEXT NULL,
  `created_at` DATETIME NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `deals` (
  `id` VARCHAR(191) NOT NULL,
  `is_ibo_player` TINYINT(1) NULL,
  `product_type` TEXT NULL,
  `number_of_users` BIGINT NULL,
  `created_at` DATETIME NULL,
  `closing_agent` VARCHAR(191) NULL,
  `data_month` BIGINT NULL,
  `duration_years` BIGINT NULL,
  `end_date` DATE NULL,
  `signup_date` DATE NULL,
  `device_id` VARCHAR(191) NULL,
  `email` VARCHAR(191) NULL,
  `updated_at` DATETIME NULL,
  `sales_agent_norm` VARCHAR(191) NULL,
  `phone_number` VARCHAR(191) NULL,
  `priority` VARCHAR(191) NULL,
  `is_bob_player` TINYINT(1) NULL,
  `paid_per_day` DOUBLE NULL,
  `sales_team` VARCHAR(191) NULL,
  `is_iboss` TINYINT(1) NULL,
  `country` VARCHAR(191) NULL,
  `customer_name` VARCHAR(191) NULL,
  `created_by_id` VARCHAR(191) NULL,
  `device_key` VARCHAR(191) NULL,
  `invoice_link` TEXT NULL,
  `stage` VARCHAR(191) NULL,
  `service_tier` VARCHAR(191) NULL,
  `closing_agent_norm` VARCHAR(191) NULL,
  `amount_paid` BIGINT NULL,
  `sales_agent` VARCHAR(191) NULL,
  `paid_per_month` DOUBLE NULL,
  `duration_months` BIGINT NULL,
  `is_ibo_pro` TINYINT(1) NULL,
  `is_above_avg` TINYINT(1) NULL,
  `paid_rank` BIGINT NULL,
  `days_remaining` BIGINT NULL,
  `custom_country` TEXT NULL,
  `agent_avg_paid` DOUBLE NULL,
  `created_by` VARCHAR(191) NULL,
  `notes` TEXT NULL,
  `end_year` BIGINT NULL,
  `data_year` BIGINT NULL,
  `is_smarters` TINYINT(1) NULL,
  `status` TEXT NULL,
  `SalesAgentID` VARCHAR(191) NULL,
  `ClosingAgentID` VARCHAR(191) NULL,
  `duration_mean_paid` DOUBLE NULL,
  `DealID` VARCHAR(191) NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `callbacks` (
  `id` VARCHAR(191) NOT NULL,
  `first_call_date` DATE NULL,
  `phone_number` VARCHAR(191) NULL,
  `first_call_time` TEXT NULL,
  `scheduled_date` DATE NULL,
  `status` TEXT NULL,
  `customer_name` VARCHAR(191) NULL,
  `created_by_id` VARCHAR(191) NULL,
  `updated_at` DATETIME NULL,
  `callback_notes` TEXT NULL,
  `created_at` DATETIME NULL,
  `follow_up_required` TINYINT(1) NULL,
  `sales_agent` VARCHAR(191) NULL,
  `SalesAgentID` VARCHAR(191) NULL,
  `created_by` VARCHAR(191) NULL,
  `email` VARCHAR(191) NULL,
  `sales_team` VARCHAR(191) NULL,
  `scheduled_time` TEXT NULL,
  `priority` VARCHAR(191) NULL,
  `callback_reason` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `target_progress` (
  `id` VARCHAR(191) NOT NULL,
  `remainingDeals` BIGINT NULL,
  `agentName` VARCHAR(191) NULL,
  `currentSales` BIGINT NULL,
  `currentDeals` BIGINT NULL,
  `created_at` DATETIME NULL,
  `progressPercentage` DOUBLE NULL,
  `lastUpdated` DATETIME NULL,
  `monthlyTarget` BIGINT NULL,
  `status` TEXT NULL,
  `targetId` TEXT NULL,
  `agentId` VARCHAR(191) NULL,
  `dealsProgressPercentage` BIGINT NULL,
  `dealsTarget` BIGINT NULL,
  `period` VARCHAR(191) NULL,
  `updated_at` DATETIME NULL,
  `remainingTarget` BIGINT NULL,
  `dealHistory` JSON NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `notifications` (
  `id` VARCHAR(191) NOT NULL,
  `message` TEXT NULL,
  `customerName` TEXT NULL,
  `to` JSON NULL,
  `actionRequired` TINYINT(1) NULL,
  `isRead` TINYINT(1) NULL,
  `timestamp` DATETIME NULL,
  `salesAgent` TEXT NULL,
  `title` TEXT NULL,
  `created_at` DATETIME NULL,
  `type` TEXT NULL,
  `callbackId` TEXT NULL,
  `salesAgentId` TEXT NULL,
  `callbackStatus` TEXT NULL,
  `priority` VARCHAR(191) NULL,
  `from` TEXT NULL,
  `customerPhone` TEXT NULL,
  `customerEmail` TEXT NULL,
  `callbackReason` TEXT NULL,
  `fromAvatar` TEXT NULL,
  `scheduledDate` DATE NULL,
  `teamName` TEXT NULL,
  `scheduledTime` TEXT NULL,
  `isManagerMessage` TINYINT(1) NULL,
  `targetId` TEXT NULL,
  `userRole` TEXT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Data Center Tables for Feedback System
CREATE TABLE IF NOT EXISTS `data_center` (
  `id` VARCHAR(255) NOT NULL,
  `title` VARCHAR(500) NOT NULL,
  `description` TEXT NOT NULL,
  `content` LONGTEXT NULL,
  `data_type` VARCHAR(100) DEFAULT 'general',
  `sent_by_id` VARCHAR(255) NOT NULL,
  `sent_to_id` VARCHAR(255) NULL,
  `sent_to_team` VARCHAR(255) NULL,
  `priority` ENUM('low', 'medium', 'high', 'urgent') DEFAULT 'medium',
  `status` ENUM('active', 'archived', 'deleted') DEFAULT 'active',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  PRIMARY KEY (`id`),
  INDEX `idx_sent_by` (`sent_by_id`),
  INDEX `idx_sent_to` (`sent_to_id`),
  INDEX `idx_sent_to_team` (`sent_to_team`),
  INDEX `idx_status` (`status`),
  INDEX `idx_priority` (`priority`),
  INDEX `idx_created_at` (`created_at`),
  INDEX `idx_data_type` (`data_type`),
  
  FOREIGN KEY (`sent_by_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`sent_to_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `data_feedback` (
  `id` VARCHAR(255) NOT NULL,
  `data_id` VARCHAR(255) NOT NULL,
  `user_id` VARCHAR(255) NOT NULL,
  `feedback_text` TEXT NOT NULL,
  `rating` INT CHECK (`rating` >= 1 AND `rating` <= 5),
  `feedback_type` VARCHAR(100) DEFAULT 'general',
  `status` ENUM('active', 'archived', 'deleted') DEFAULT 'active',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  PRIMARY KEY (`id`),
  INDEX `idx_data_id` (`data_id`),
  INDEX `idx_user_id` (`user_id`),
  INDEX `idx_status` (`status`),
  INDEX `idx_created_at` (`created_at`),
  INDEX `idx_rating` (`rating`),
  INDEX `idx_feedback_type` (`feedback_type`),
  
  FOREIGN KEY (`data_id`) REFERENCES `data_center`(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

